---
- name: implementing tags
  hosts: all
  tasks:
   - name: install tree
     apt:
      name: tree
      state: present
     tags: tree_installation
   - name: create a user
     user:
      name: rahul
      password: intelliq
     tags: user_creation
   - name: copy the passwd file
     copy:
      src: /etc/passwd
      dest: /tmp
...
