---
- name: creating user and downloading files into users home directory
  hosts: all
  tasks:
   - name: create users
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: downloading files
     get_url:
      url: "{{d}}"
      dest: "{{e}}"
...
